[package]
name = "m2ground"
version = "0.1.0"
authors = ["Adam Greig <adam@adamgreig.com>"]

[dependencies.modem]
path = "modem"

[dependencies.sdr]
path = "sdr"

[dependencies.ldpcd]
path = "ldpcd"

[lib]
name = "m2ground"
crate-type = ["dylib", "rlib"]
path = "src/lib.rs"
